### PR TITLE
Return rows as maps

### PR DESCRIPTION
**Pull request by benjamin-bergia**
Same as https://github.com/semiocast/pgsql/pull/36 just re-open on a different branch.

### CODE REVIEW

**Comment by tsloughter** [comment]
Any news on this/? :)

**Comment by ehamberg** [comment]
(Only fails on Erlang/OTP 16 since there is no maps support there.)

`src/pgsql_connection.erl:104: type map() undefined`

**Comment by pguyot** [comment]
True. Is it a problem? I silently considered that we could drop support for R16 and updated travis CI matrix accordingly.

**Comment by ehamberg** [comment]
Most likely not. I'm in favour of dropping R16 support. :)

**Pull request merged**
